package com.reminder.app.domain.model

/**
 * Domain model. Kept independent of Room so use cases and the UI never depend on
 * persistence annotations. [id] is 0 until Room assigns an autogenerated primary key.
 */
data class Reminder(
    val id: Long,
    val title: String,
    /** Wall-clock trigger time, milliseconds since epoch in the device time zone. */
    val triggerTimeMillis: Long,
    val status: ReminderStatus
)
